<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\UserModel;

class TemplateSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        // 1. Seed Template Categories
        $templateCategories = [
            [
                'name'       => 'Kerangka Kerja Acuan',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
        $this->db->table('template_categories')->insertBatch($templateCategories);

        // 2. Seed Templates
        $templateData = [
            [
                'name'           => 'Spesifikasi Pekerjaan Barang',
                'slug'           => 'spesifikasi_pekerjaan_barang',
                'category_id'    => 1,
                'description'    => 'Template untuk Kerangka Acuan Kerja Spesifikasi Pekerjaan Barang',
                'file_path'      => '/template/Spesifikasi Pekerjaan Barang - Template.docx',
                'file_name'      => 'Spesifikasi Pekerjaan Barang - Template',
                'uploaded_by'    => 1,
                'is_active'      => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'name'           => 'Spesifikasi Pekerjaan Jasa Konsultansi',
                'slug'           => 'spesifikasi_pekerjaan_jasa_konsultansi',
                'category_id'    => 1,
                'description'    => 'Template untuk Kerangka Acuan Kerja Spesifikasi Pekerjaan Jasa Konsultansi',
                'file_path'      => '/template/Spesifikasi Pekerjaan Jasa Konsultansi - Template.docx',
                'file_name'      => 'Spesifikasi Pekerjaan Jasa Konsultansi - Template',
                'uploaded_by'    => 1,
                'is_active'      => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'name'           => 'Spesifikasi Pekerjaan Jasa Lainnya',
                'slug'           => 'spesifikasi_pekerjaan_jasa_lainnya',
                'category_id'    => 1,
                'description'    => 'Template untuk Kerangka Acuan Kerja Spesifikasi Pekerjaan Jasa Lainnya',
                'file_path'      => '/template/Spesifikasi Pekerjaan Jasa Lainnya - Template.docx',
                'file_name'      => 'Spesifikasi Pekerjaan Jasa Lainnya - Template',
                'uploaded_by'    => 1,
                'is_active'      => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'name'           => 'Spesifikasi Pekerjaan Konstruksi RKST',
                'slug'           => 'spesifikasi_pekerjaan_konstruksi_rkst',
                'category_id'    => 1,
                'description'    => 'Template untuk Kerangka Acuan Kerja Spesifikasi Pekerjaan Konstruksi RKST',
                'file_path'      => '/template/Spesifikasi Pekerjaan Konstruksi RKST - Template.docx',
                'file_name'      => 'Spesifikasi Pekerjaan Konstruksi RKST - Template',
                'uploaded_by'    => 1,
                'is_active'      => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'name'           => 'Spesifikasi Pekerjaan Konsultansi Konstruksi RKST',
                'slug'           => 'spesifikasi_pekerjaan_konsultansi_konstruksi_rkst',
                'category_id'    => 1,
                'description'    => 'Template untuk Kerangka Acuan Kerja Spesifikasi Pekerjaan Konsultansi Konstruksi RKST',
                'file_path'      => '/template/Spesifikasi Pekerjaan Konsultansi Konstruksi RKST - Template.docx',
                'file_name'      => 'Spesifikasi Pekerjaan Konsultansi Konstruksi RKST - Template',
                'uploaded_by'    => 1,
                'is_active'      => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ]
        ];
        $this->db->table('templates')->insertBatch($templateData);

        // 3. Seed Template Fields
        $templateFieldsData = [
            [
                'template_id'         => 1,
                'field_key'           => 'NAMA_BARANG',
                'field_label'         => 'Nama Barang',
                'field_type'          => 'text',
                'field_order'         => 1,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'NAMA_UNIT_KERJA',
                'field_label'         => 'Nama Unit Kerja',
                'field_type'          => 'text',
                'field_order'         => 2,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'TAHUN_ANGGARAN',
                'field_label'         => 'Tahun Anggaran',
                'field_type'          => 'text',
                'field_order'         => 3,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'nama_pekerjaan',
                'field_label'         => 'Nama Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 4,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'referensi',
                'field_label'         => 'Referensi',
                'field_type'          => 'text',
                'field_order'         => 5,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'mencantumkan rujukan referensi dasar pelaksanaan pekerjaan dan/atau referensi standar teknis barang',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'ruang_lingkup_pekerjaan',
                'field_label'         => 'Ruang Lingkup Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 6,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan ruang lingkup pekerjaan seperti :
                                            - Penyediaan barang
                                            - Pengemasan
                                            - Pengiriman
                                            - Pemeriksaan mutu/kesesuaian spesifikasi, tindak lanjut apabila terdapat ketidaksesuaian
                                            - Serah terima barang.
                                            ',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'lokasi_pekerjaan',
                'field_label'         => 'Lokasi Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 7,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan lokasi pelaksanaan pekerjaan atau lokasi penyerahan barang.',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'spesifikasi_teknis_barang',
                'field_label'         => 'Spesifikasi Teknis Barang',
                'field_type'          => 'text',
                'field_order'         => 8,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan spesifikasi teknis barang yang dibutuhkan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'jangka_waktu_pekerjaan',
                'field_label'         => 'Jangka Waktu Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 9,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan jangka waktu pelaksanaan pekerjaan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'penggunaan_produk_dalam_negeri',
                'field_label'         => 'Penggunaan Produk Dalam Negeri',
                'field_type'          => 'text',
                'field_order'         => 10,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'narasi penggunaan produk dalam negeri',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'jenis_kontrak',
                'field_label'         => 'Jenis Kontrak',
                'field_type'          => 'text',
                'field_order'         => 11,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan jenis kontrak yang digunakan seperti :
                                            -Kontrak Payung
                                            -Kontrak Lumsum
                                            -Kontrak Harga Satuan
                                            -Kontrak gabungan lumsum dan harga satuan
                                          ',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'mekanisme_pembayaran_termin_pembayaran',
                'field_label'         => 'Mekanisme Pembayaran Termin Pembayaran',
                'field_type'          => 'text',
                'field_order'         => 12,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan :
                                            -	Mekanisme pembayaran apakah menggunakan sistem transfer atau SKBDN, jangka waktu pembayaran (.... hari setelah dokumen tagihan lengkap).
                                            -	Apakah pembayaran dilakukan sekaligus (dalam satu tahap) ketika pekerjaan selesai atau menggunakan beberapa tahap (termin) berdasarkan progres pekerjaan serta besaran pembayaran untuk setiap tahapannya
                                        ',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'bill_of_quantity',
                'field_label'         => 'Bill Of Quantity',
                'field_type'          => 'text',
                'field_order'         => 13,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan rincian jumlah barang yang dibutuhkan.',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'kualifikasi_teknis_perusahaan_penyedia',
                'field_label'         => 'Kualifikasi Teknis Perusahaan Penyedia',
                'field_type'          => 'text',
                'field_order'         => 14,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan kualifikasi teknis yang harus dipenuhi oleh perusahaan penyedia dalam melaksanakan pekerjaan seperti pengalaman perusahaan, penerapan sistem manajemen, sertifikasi dan sebagainya',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'metode_evaluasi_penawaran',
                'field_label'         => 'Metode Evaluasi Penawaran',
                'field_type'          => 'text',
                'field_order'         => 15,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan metode evaluasi penyeleksian seperti: metode evaluasi harga terendah, sistem nilai, total cost of ownership, Discount Factor',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'kriteria_dan_bobot_penilaian',
                'field_label'         => 'Kriteria dan Bobot Penilaian',
                'field_type'          => 'text',
                'field_order'         => 16,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan kriteria dan bobot penilaian jika metode evaluasi menggunakan sistem nilai.',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'penutup',
                'field_label'         => 'Penutup',
                'field_type'          => 'text',
                'field_order'         => 17,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'nama_divisi',
                'field_label'         => 'Nama Divisi',
                'field_type'          => 'text',
                'field_order'         => 18,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'nama_pejabat',
                'field_label'         => 'Nama Pejabat',
                'field_type'          => 'text',
                'field_order'         => 19,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 1,
                'field_key'           => 'jabatan',
                'field_label'         => 'Jabatan',
                'field_type'          => 'text',
                'field_order'         => 20,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'NAMA_PEKERJAAN',
                'field_label'         => 'Nama Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 1,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,   
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'NAMA_UNIT_KERJA',
                'field_label'         => 'Nama Unit Kerja',
                'field_type'          => 'text',
                'field_order'         => 2,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'TAHUN_PEKERJAAN',
                'field_label'         => 'Tahun Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 3,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'nama_pekerjaan',
                'field_label'         => 'Nama Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 4,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'referensi',
                'field_label'         => 'Referensi',
                'field_type'          => 'richtext',
                'field_order'         => 5,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'mencantumkan rujukan referensi dasar pelaksanaan pekerjaan dan/atau referensi standar teknis pekerjaan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'nama_spesifikasi_pekerjaan',
                'field_label'         => 'Nama Spesifikasi Pekerjaan ( Footer )',
                'field_type'          => 'text',
                'field_order'         => 6,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'ruang_lingkup_pekerjaan',
                'field_label'         => 'Ruang Lingkup Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 7,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => '*menjelaskan apa saja yang menjadi ruang lingkup pekerjaan, seperti :
                                                -	Persiapan pekerjaan
                                                -	Pelaksanaan pekerjaan
                                                -	Pemeriksaan mutu/kesesuaian spesifikasi dan tindak lanjut apabila terdapat ketidaksesuaian
                                                -	Serah terima pekerjaan.
                                            ',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'lokasi_pekerjaan',
                'field_label'         => 'Lokasi Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 8,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan lokasi/tempat dilaksanakan pekerjaan, apakah di satu tempat atau di beberapa tempat',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'standar_teknis',
                'field_label'         => 'Standar Teknis',
                'field_type'          => 'text',
                'field_order'         => 9,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan standar teknis pekerjaan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'kualifikasi_dan_jumlah_tenaga_yang_harus_disediakan',
                'field_label'         => 'Kualifikasi dan Jumlah Tenaga yang Harus Disediakan',
                'field_type'          => 'text',
                'field_order'         => 10,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan kualifikasi dan jumlah tenaga yang harus disediakan penyedia dalam melaksanakan pekerjaan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'peralatan_dan_bahan_material_yang_harus_disediakan',
                'field_label'         => 'Peralatan dan Bahan Material yang Harus Disediakan',
                'field_type'          => 'text',
                'field_order'         => 11,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan apabila terdapat peralatan dan bahan (material) yang harus disediakan penyedia',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'jangka_waktu_pekerjaan',
                'field_label'         => 'Jangka Waktu Pekerjaan',
                'field_type'          => 'text',
                'field_order'         => 12,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan jangka waktu pekerjaan',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'penggunaan_produk_dalam_negeri',
                'field_label'         => 'Penggunaan Produk Dalam Negeri',
                'field_type'          => 'text',
                'field_order'         => 13,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'narasi penggunaan produk dalam negeri',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'jenis_kontrak',
                'field_label'         => 'Jenis Kontrak',
                'field_type'          => 'text',
                'field_order'         => 14,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan jenis kontrak yang digunakan seperti :
                                            -Kontrak Payung
                                            -Kontrak Lumsum
                                            -Kontrak Harga Satuan
                                            -Kontrak gabungan lumsum dan harga satuan
                                        ',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'mekanisme_pembayaran_termin_pembayaran',
                'field_label'         => 'Mekanisme Pembayaran Termin Pembayaran',
                'field_type'          => 'text',
                'field_order'         => 15,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan :
                                            - Mekanisme pembayaran apakah menggunakan sistem transfer atau SKBDN, jangka waktu pembayaran (.... hari setelah dokumen tagihan lengkap).
                                            -	Apakah pembayaran dilakukan sekaligus (dalam satu tahap) ketika pekerjaan selesai atau menggunakan beberapa tahap (termin) berdasarkan progres pekerjaan serta besaran pembayaran untuk setiap tahapannya.
                                         ',
                'created_at'          => $now,
            
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'bill_of_quantity',
                'field_label'         => 'Bill of Quantity',
                'field_type'          => 'text',
                'field_order'         => 16,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan rincian jumlah barang dan/atau bahan yang dibutuhkan.',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'kualifikasi_teknis_perusahaan_penyedia',
                'field_label'         => 'Kualifikasi Teknis Perusahaan Penyedia',
                'field_type'          => 'text',
                'field_order'         => 17,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan kualifikasi teknis yang harus dipenuhi oleh perusahaan penyedia dalam melaksanakan pekerjaan seperti pengalaman perusahaan, penerapan sistem manajemen, sertifikasi dan sebagainya.',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'metode_evaluasi_penawaran',
                'field_label'         => 'Metode Evaluasi Penawaran',
                'field_type'          => 'text',
                'field_order'         => 18,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan metode evaluasi penyeleksian seperti : metode evaluasi harga terendah, sistem nilai, total cost of ownership, Discount Factor',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'kriteria_dan_bobot_penilaian_teknis',
                'field_label'         => 'Kriteria dan Bobot Penilaian Teknis',
                'field_type'          => 'text',
                'field_order'         => 19,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'menjelaskan kriteria apa saja yang menjadi penilaian dan bobot penilaian untuk tiap kriteria. Pengisian kriteria diperlukan jika metode evaluasi menggunakan sistem nilai',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'penutup',
                'field_label'         => 'Penutup',
                'field_type'          => 'text',
                'field_order'         => 20,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => 'narasi penutup',
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'nama_divisi',
                'field_label'         => 'Nama Divisi',
                'field_type'          => 'text',
                'field_order'         => 21,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'nama_pejabat',
                'field_label'         => 'Nama Pejabat',
                'field_type'          => 'text',
                'field_order'         => 22,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],
            [
                'template_id'         => 3,
                'field_key'           => 'jabatan',
                'field_label'         => 'Jabatan',
                'field_type'          => 'text',
                'field_order'         => 23,
                'is_required'         => 1,
                'default_value'       => null,
                'terbilang_target_id' => null,
                'is_auto_generated'   => 0,
                'information'         => null,
                'created_at'          => $now,
            ],

        ];
        $this->db->table('template_fields')->insertBatch($templateFieldsData);

        echo "Seeder berhasil dijalankan!\n";
    }
}